### PR TITLE
Implement support for custom content types

### PR DESCRIPTION
**Pull request by kibertoad**
refs #2 

Not sure if it covers scope of original issue completely, but at least it enables usage of JSON+HAL content type, which is an improvement :)

### CODE REVIEW

**Comment by kibertoad** [comment]
@kobik Does this make sense to you :)?

**Comment by kibertoad** [comment]
We've already tested this in combination with https://github.com/Zooz/api-contract-validator/pull/18, seems to work just fine with JSON+HAL with real-world schemas.

**Comment by kobik** [comment]
@kibertoad, thanks for the PR :)

As multiple content-types can be supported simultaneously as can be seen [here](https://swagger.io/docs/specification/describing-responses/), the proper solution would be to iterate the response content array and add a validator for each content-type.

I assume that this would require more work, but IMO, this is the way should go.

**Comment by kibertoad** [comment]
@kobik Sure, no problem, I can implement that. So to clarify: you would like user to be able to pass an array as a value for `responseContentType` and `requestContentType`?

**Comment by kibertoad** [comment]
Or you mean that it shouldn't be a config parameter at all, but iteration should happen over every content-type defined in schema?

**Comment by kobik** [comment]
> Or you mean that it shouldn't be a config parameter at all, but iteration should happen over every content-type defined in schema?

This :+1:

**Comment by kibertoad** [comment]
@kobik OK, I've mostly finished implementing this, however, while working on it I've realized that this would be a breaking change, since instead of current
```
        schemas[path][method].body.validate(body)) 
```
call, users would need to do
```
        schemas[path][method].body[contentType].validate(body)) 
```

Hence my proposal would be this: merge current PR as-is (since it is non-breaking and covers the most typical use-case, which is single content-type), then I'll create a follow-up PR with implementation that would support multiple content-types, and also create a PR which would update express-ajv-swagger-validator to support new multi-content-type logic. Does that make sense?

**Comment by kibertoad** [comment]
@kobik Superseded by #25, which, as requested, supports multiple content types and reads them from schema itself.

**Pull request closed without merging**
